#cloud-config

package_update: true
packages:
  - docker
  - docker-compose
  - gnupg2
  - pass


runcmd:
 - sleep 10
 - docker login ${docker_registry} --username ${docker_registry_username} --password ${docker_registry_password}
 - docker-compose -f ${root_directory}/docker-compose.yml up -d