#cloud-config

package_update: true
packages:
  - docker
  - docker-compose
  - gnupg2
  - pass


runcmd:
 - /usr/bin/sleep 10
 - /usr/bin/docker login ${docker_registry} --username ${docker_registry_username} --password ${docker_registry_password}
 - cd /opt/node
 - /usr/bin/docker-compose up -d